const auth ={
    USER_LOGOUT :'USER_LOGOUT',
    AUTH_CALLBACK_ERROR : 'AUTH_CALLBACK_ERROR',
    AUTH_CALLBACK_SUCCESS : 'AUTH_CALLBACK_SUCCESS',
    AUTH_SET_REDIRECT : 'AUTH_SET_REDIRECT'
}
export default auth